import type { Metadata } from "next";
import { Bevan, Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const titleFont = Bevan({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-title"
});

const textFont = Poppins({
    weight: "400",
    subsets: ["latin"],
    variable: "--font-text"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(titleFont.variable, textFont.variable)}>
                {children}
            </body>
        </html>
    );
}
